### PR TITLE
navbar is addded to the code

### PR DESCRIPTION
**Pull request by striverz010**
# The super built nav bar is added to the code

- one
- two
- three

### CODE REVIEW

**Comment by striverz011** [comment]
# please add the footer as well to the code

**Comment by striverz010** [comment]
yes i will do wait...

**Comment by striverz011** [comment]
ok i am waitir do fast

**Comment by striverz010** [comment]
> ok i am waitir do fast

it will take 100rs to do this so

**Comment by striverz011** [comment]
ok take then

**Comment by striverz010** [comment]
ok with in 5 days the code is going to ready ok

**Comment by striverz011** [comment]
ok

**Pull request merged**
